version: "3"

services:
  db:
    #migrate migrate -path ./web/schema -database 'postgres://user:password@localhost:5431/distr?sslmode=disable' up
    image: postgres:13.3
    environment:
      POSTGRES_DB: "distr"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: 22334455
  web:
    build: ./web
    command: ./main
    ports:
      - "8080:8080"
    links:
      - db
      - rabbit
    depends_on:
      - db
      - rabbit
    restart: on-failure

  caller:
    build: ./apiCaller
    command: ./main
    ports:
      - "8001:8081"
    links:
      - rabbit
      - web
    depends_on:
      - rabbit
    restart: on-failure