port: "8000"
rabbit_user: "myuser"
rabbit_password: "22334455"
rabbit_port: "5672"
queue_name: "repo"
db_url: "postgres://user:password@db:5431/distr?sslmode=disable"
GITHUB_OAUTH__CLIENT_ID: "b76f24e4391dc2f6fdf7"
GITHUB_OAUTH_CLIENT_SECRET: "bd9ee177bb0c24ac33cfaa647cfa3fee77d0e759"
GITHUB_OAUTH_REDIRECT_URL: "http://localhost:80/oauth/sign-in"